################## Eureka Configuration ####################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3001/eureka/, http://localhost:3002/eureka/, http://localhost:3003/eureka/

################## Application Settings ####################
spring:
  application:
    name: SSO-AUTH-SERVER

  datasource:
    jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      jwt:
        alias: server_private
        code: mid@sit
        expired: 1
        public: /publicKey.txt
        private: /server.jks

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: ${PORT:9000}
  servlet:
    context-path: /auth
